#!/usr/bin/env ansible-playbook
---
# Prepartion for installation for OpenShift Container Platform 3.3
- name: Prepare hosts for OpenShift Container Platform 3.3
  hosts: openshift_hosts
  vars:
    prereqs_packages:
      - vim
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - docker
      - httpd-tools
    docker_device: /dev/xvdb
    docker_device_partition: /dec/xvdb1 
  tasks:
    - name: Setting the hostname
      copy: dest=/etc/hostname content="{{ ansible_host }}"

    - name: Setting all the necessary repositories 
      include: repositories.yaml      

    - name: "Update All"
      yum: name='*' state=latest update_cache=yes

    - name: "Installing Basic Applications"
      yum: name="{{ item }}" state=present
      with_items: prereqs_packages

    - name: Create a partition for Docker
      command: parted {{ docker_device }} --script 'mklabel msdos mkpart primary 0% 100%'

    - name: Create a VG named docker-vg (used for Docker)
      lvg: vg=docker-vg pvs={{ docker_device_partition }}

    - name: Configuring Docker-Storage-Setup first
      lineinfile: dest=/etc/sysconfig/docker-storage-setup line="VG=docker-vg"

    - name: Run a Docker-Storage-Setup
      command: /usr/bin/docker-storage-setup 

    - name: Setting Docker configuration with with the correct info
      lineinfile: dest=/etc/sysconfig/docker regexp="OPTIONS=.*" line="OPTIONS=\"--selinux-enabled --insecure-registry 172.30.0.0/16  --log-driver=journald\""

    

