---
- name: Installing Red Hat Mobile Application Platform 4.2
  hosts: localhost
  connection: local
  vars: 
     smtp_server: "localhost"
     smtp_username: "username"
     smtp_password: "password"
     smtp_from_address: "nagios@example.com"
     admin_email:  "root@localhost"
  roles: 
     - core
     - mbaas
