---
- name: Installing Gogs
  hosts: localhost
  connection: local
  vars:
     - gogs_username: gogs
     - gogs_password: gogs
     - gogs_database_type: PostgreSQL
     - namespace: tool
  tasks:

     - name: Retrieving Gogs Database's Username
       command: oc get deploymentconfig/postgresql-gogs -o jsonpath="{.spec.template.spec.containers[*].env[?(@.name==\"POSTGRESQL_USER\")].value}" --namespace {{ namespace }}
       register: gogs_database_username

     - name: Retrieving Gogs Database's Password
       command: oc get deploymentconfig/postgresql-gogs -o jsonpath="{.spec.template.spec.containers[*].env[?(@.name==\"POSTGRESQL_PASSWORD\")].value}" --namespace {{ namespace }}
       register: gogs_database_password

     - name: Retrieving Gogs Database's Name
       command: oc get deploymentconfig/postgresql-gogs -o jsonpath="{.spec.template.spec.containers[*].env[?(@.name==\"POSTGRESQL_DATABASE\")].value}" --namespace {{ namespace }}
       register: gogs_database_name

     - name: Retrieving Gogss Database's IP
       command: oc get service/postgresql-gogs --output template --template "{{ '{{' }}.spec.clusterIP{{ '}}' }}" --namespace {{ namespace }}
       register: gogs_database_ip

     - name: Retrieving Gog's Port Number
       command: oc get service/gogs --output jsonpath="{.spec.ports.*.port}" --namespace {{ namespace }}
       register: gogs_database_port

     - debug: msg="Username {{ gogs_database_username.stdout }}"

     - name: Installing Gogs for the very first time
       uri: method=POST HEADER_Content-type="application/x-www-form-urlencoded" url="http://gogs.cloudapps.example.com/install"
            body="db_type={{ gogs_database_type | urlencode }}&db_host=172.30.146.17%3A5432&db_user=user4X4&db_passwd=LceaTgy3mahqCdNg&db_name=gogs&ssl_mode=disable&db_path=data%2Fgogs.db&app_name=Gogs%3A+Go+Git+Service&repo_root_path=%2Fhome%2Fgogs%2Fgogs-repositories&run_user=gogs&domain=localhost&ssh_port=22&http_port=3000&app_url=http%3A%2F%2Fgogs.cloudapps.example.com%2F&log_root_path=%2Fopt%2Fgogs%2Flog&admin_name=mauricio&admin_passwd=maltron&admin_confirm_passwd=maltron&admin_email=admin%40gogs.com"
