---
# Prepartion for installation for OpenShift Container Platform 3.3
- name: Prepare hosts for OpenShift Container Platform 3.3
  hosts: master.example.com
  vars:
    prereqs_packages:
      - vim
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - docker
      - http-tools
  tasks:
    - name: Set the hostname for each node
      command: echo {{ ansible_host }}
    - name: Setting the hostname
      lineinfile: dest=/etc/hostname regexp='^' line='{{ ansible_host }}'
    - name: "Adding Repository: Red Hat Enterprise Linux 7"
      yum_repository: 
          name: server-rpms
          description: Red Hat Enterprise Linux 7
          baseurl: http://oselab.example.com/repos/3.3/rhel-7-server-rpms http://www.opentlc.com/repos/ose/3.3/rhel-7-server-rpms
          enabled: yes
          gpgcheck: no
      yum_repository: 
          name: rhel-7-server-rh-common-rpms
          description: Red Hat Enterprise Linux 7 Common
          baseurl: http://oselab.example.com/repos/3.3/rhel-7-server-rh-common-rpms http://www.opentlc.com/repos/ose/3.3/rhel-7-server-rh-common-rpms
          enabled: yes
          gpgcheck: no
    - name: "Adding Repository: Red Hat Enterprise Linux 7 Extras"
      yum_repository:
          name: rhel-7-server-extras-rpms
          description: Red Hat Enterprise Linux 7 Extras
          baseurl: http://oselab.example.com/repos/3.3/rhel-7-server-extras-rpms http://www.opentlc.com/repos/ose/3.3/rhel-7-server-extras-rpms
          enabled: yes
          gpgcheck: no
    - name: "Adding Repository: Red Hat Enterprise Linux 7 Optional"
      yum_repository:
          name: rhel-7-server-extras-rpms
          description: Red Hat Enterprise Linux 7 Optional
          baseurl: http://oselab.example.com/repos/3.3/rhel-7-server-optional-rpms http://www.opentlc.com/repos/ose/3.3/rhel-7-server-optional-rpms
          enabled: yes
          gpgcheck: no
    - name: "Adding Repository: Red Hat Enterprise Linux 7 OSE $VERSION"
      yum_repository:
          name: rhel-7-server-ose-3.3-rpms
          description:  Red Hat Enterprise Linux 7 OSE $VERSION
          baseurl: http://oselab.example.com/repos/3.3/rhel-7-server-ose-3.3-rpms http://www.opentlc.com/repos/ose/3.3/rhel-7-server-ose-3.3-rpms
          enabled: yes
          gpgcheck: no
